name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run tests (parking_lot)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features pl
      - name: Check for clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for clippy warnings (parking_lot)
        uses: actions-rs/clippy-check@v1
        with:
          args: --features pl
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
